### ISSUE TITLE
[Feature] run playbook in Ubuntu on Windows

### ISSUE THREAD

**Issue by zikalino** [VSChina/vscode-ansible#103]
## Environment
- OS Type: Windows

## Summary
There should be an option to run playbook locally in Bash on Ubuntu on Windows, as this is probably the easier way to use Ansible on Windows.

**Comment by yungezz** [comment]
@zikalino  thanks for providing the suggestion. Currently we provide run playbook inside docker, and via ssh option for windows users. Could you pls give them a try and let us know if any feedback? Bash on Ubuntu isn't a common scenario for windows user. We need evaluate it with some data. We're not trying to build an extension which meet requirements of all scenarios, but a common extension meets majority users' scenario. Let's discuss this with some survey and data to help understand how many user is using Ubuntu bash on windows.

**Comment by nhok** [comment]
maybe it is worth thinking about this, i use ansible from cygwin shell in windows, this works very well, if the ansible plugin can be set up to use a specific shell, this would be really cool

**Comment by murrahjm** [comment]
Windows Subsystem for Linux (WSL) is growing rapidly in popularity, as is the use of Ansible to manage Windows systems.  VSCode + WSL + Ansible is a fantastic editing and management platform.

Maybe a right-click option to run in custom shell and then an extension preference item to specify the shell to run it in would cover many options.

**Comment by kkolk** [comment]
I couldn't agree more, the docker based method seems less native to me then
using WSL and clumsy.  I've been using WSL manually instead to test Ansible
playbooks on Windows for more than a year and it's my go-to method.  I'd
love to see this supported.

**Comment by rmcolbert** [comment]
This may not be the most elegant solution, but I added WSL support in this pull request.
#215

**Comment by 2fst4u** [comment]
Commenting to add support for this request. I can't seem to get Ansible to work even when editing in WSL as the "Run Ansible playbook in local Ansible" opens in the host machine's idea of "local" rather than the editor's remote instance.

This would be really great to add.

**Comment by l3ender** [comment]
> I can't seem to get Ansible to work even when editing in WSL as the "Run Ansible playbook in local Ansible" opens in the host machine's idea of "local" rather than the editor's remote instance.

I am facing the same. VSCode 1.51.1, Ansible extension 0.5.2, and Ubuntu 20.04 on WSL2.

**Comment by l3ender** [comment]
When opening an Ansible file in WSL remote VSCode, I am seeing the following in Output terminal for Log (Remote Extension Host):

```
[2020-11-25 14:34:52.405] [exthost] [error] Activating extension vscoss.vscode-ansible failed due to an error:
[2020-11-25 14:34:52.408] [exthost] [error] Error: Cannot find module '/home/ross/.vscode-server/extensions/vscoss.vscode-ansible-0.5.2/out/extension'
Require stack:
- /home/ross/.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f/out/vs/loader.js
- /home/ross/.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f/out/bootstrap-amd.js
- /home/ross/.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f/out/bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
	at Function.Module._load (internal/modules/cjs/loader.js:686:27)
	at Function.t._load (/home/ross/.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f/out/vs/server/remoteExtensionHostProcess.js:1088:776)
	at Function.i._load (/home/ross/.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f/out/vs/server/remoteExtensionHostProcess.js:1058:665)
	at Function.n._load (/home/ross/.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f/out/vs/server/remoteExtensionHostProcess.js:1054:844)
	at Module.require (internal/modules/cjs/loader.js:848:19)
	at require (internal/modules/cjs/helpers.js:74:18)
	at Function.s [as __$__nodeRequire] (/home/ross/.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f/out/vs/loader.js:34:963)
	at p._loadCommonJSModule (/home/ross/.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f/out/vs/server/remoteExtensionHostProcess.js:1059:939)
	at p._doActivateExtension (/home/ross/.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f/out/vs/server/remoteExtensionHostProcess.js:956:27)
	at p._activateExtension (/home/ross/.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f/out/vs/server/remoteExtensionHostProcess.js:954:946)
	at Object.actualActivateExtension (/home/ross/.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f/out/vs/server/remoteExtensionHostProcess.js:952:642)
	at h._activateExtension (/home/ross/.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f/out/vs/server/remoteExtensionHostProcess.js:690:603)
	at /home/ross/.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f/out/vs/server/remoteExtensionHostProcess.js:690:281
	at Array.map (<anonymous>)
	at h._activateExtensions (/home/ross/.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f/out/vs/server/remoteExtensionHostProcess.js:690:269)
	at h.activateByEvent (/home/ross/.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f/out/vs/server/remoteExtensionHostProcess.js:687:745)
	at p._activateByEvent (/home/ross/.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f/out/vs/server/remoteExtensionHostProcess.js:953:508)
	at /home/ross/.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f/out/vs/server/remoteExtensionHostProcess.js:962:446
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

**Comment by rmcolbert** [comment]
@l3ender This may be a dumb question ... but did you install the Ansible extension inside the WSL host?

**Comment by l3ender** [comment]
@rmcolbert Yes, I did.
